---

- hosts: nagios_servers
  become: true
  tasks:

  - name: Install Nagios (Ubuntu)
    apt:
      name:
        - nagios4
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
